name    'gehel-duplicity'
version '1.0.0'
author  'Guillaume Lederrey'
license 'Apache2'
project_page ''
source  'https://github.com/gehel/puppet-duplicity'
summary 'Puppet module for duplicity'
description 'This module installs and manages duplicity. Check README for details.'
dependency 'example42/puppi', '>= 2.0.0'
dependency 'puppetlabs-stdlib', '>=4.1.0'
# dependency 'example42/monitor', '>= 2.0.0'
# dependency 'example42/firewall', '>= 2.0.0'
